### ISSUE TITLE
Grobe Typst-Berichtsvorlage erstellen

### ISSUE THREAD

**Issue by sageorca** [bildungsplanungZH/biplaRquarto#5]
Nützliche Links:
- Quarto-Doku: https://quarto.org/docs/output-formats/typst.html
- Typst-Doku: https://typst.app/docs/tutorial/making-a-template/

```[tasklist]
### Tasks
- [ ] Titelseite mit Logo und Organisationseinheiten sowie Spickel in blau
- [ ] Kopf- und Fusszeilen für restliches Dokument analog LaTeX-Template
- [ ] Schriftgrössen und Schriftarten analog Latex-Template
```

**Comment by sageorca** [comment]
Ungefähre Vorlage ist erstellt. Es gibt noch folgende Baustellen:
* linker Seitenrand auf der Titelseite muss angepasst werden (#69 )
* `use_quarto()` muss für die Verwendung von `biplaR-typst` angepasst werden (#68)
